### PR TITLE
get_code.py

### PR DESCRIPTION
**Pull request by Gitmaccies**

### CODE REVIEW

**Comment by sapphire-bt** [comment]
?

**Comment by Gitmaccies** [comment]
Sorry mate was just messing abt w it tryna figure out how to use it to get
the free code. I’ve never used github before.

**Comment by sapphire-bt** [comment]
No worries. If it helps, here's a little demo page: https://jsfiddle.net/ug29acn8/

**Comment by Gitmaccies** [comment]
nice one mate, works perfectly

**Pull request closed without merging**
